// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AskAssistant queues a typed question. It returns as soon as the request is
 * accepted; the answer arrives through the assistant event.
 */
export function AskAssistant(question: string): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.AskAssistant", question);
}

export function Bootstrap(): $CancellablePromise<$models.AppSnapshot> {
    return $Call.ByName("main.DesktopService.Bootstrap");
}

export function ClearAssistant(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.ClearAssistant");
}

export function CopyHistory(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.CopyHistory");
}

/**
 * HideConsole takes the console off the screen without stopping recognition.
 * The tray icon brings it back, which is why the tray is created before the
 * window can ever be hidden.
 */
export function HideConsole(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.HideConsole");
}

export function InstallResource(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.InstallResource", id);
}

export function OpenSettings(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.OpenSettings");
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.Pause");
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.Quit");
}

export function RefreshResources(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.RefreshResources");
}

export function RemoveResource(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.RemoveResource", id);
}

export function ResetConsoleWindow(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.ResetConsoleWindow");
}

/**
 * SetAudioChannels replaces the audio inputs captured together, in the order
 * they should appear on screen. Every input gets its own recognizer while a run
 * is active, so a second one costs another copy of the model in memory and
 * another decoder on the CPU.
 */
export function SetAudioChannels(channels: $models.AudioChannelInput[] | null): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.SetAudioChannels", channels);
}

export function SetConfig(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.SetConfig", key, value);
}

/**
 * SetLocked pins the console where it is. The window keeps receiving mouse
 * events — the message stream still scrolls and the assistant still answers —
 * so locking only takes away moving and resizing. Dragging is a frontend drag
 * region the console drops while locked; resizing is the frontend edge handler
 * Wails only arms for a resizable window.
 */
export function SetLocked(locked: boolean): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.SetLocked", locked);
}

export function SetPluginConfig(key: string, values: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.SetPluginConfig", key, values);
}

export function ShowConsole(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.ShowConsole");
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.Start");
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByName("main.DesktopService.Stop");
}

/**
 * TestAssistant sends one throwaway request so the user can verify an endpoint
 * before enabling the assistant.
 */
export function TestAssistant(): $CancellablePromise<string> {
    return $Call.ByName("main.DesktopService.TestAssistant");
}
