// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as assistant$0 from "./internal/assistant/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as job$0 from "./internal/job/models.js";

export interface AppSnapshot {
    "status": job$0.Status;
    "runningSeconds": number;
    "text": string;
    "channels": job$0.ChannelState[] | null;
    "locked": boolean;
    "history": job$0.HistoryEntry[] | null;
    "config": { [_ in string]?: any } | null;
    "audioSources": PluginOption[] | null;
    "recognizers": PluginOption[] | null;
    "resources": ResourceItem[] | null;

    /**
     * PunctuationModels are the installed punctuation resources, by resolved
     * model path, so the settings page can offer them instead of asking for a
     * path typed by hand.
     */
    "punctuationModels": ConfigFieldOption[] | null;
    "assistant": assistant$0.State;
    "version": string;
    "commit": string;
    "platform": string;
    "lastError"?: string;
}

/**
 * AudioChannelInput is one labeled audio input as the settings page sends it.
 */
export interface AudioChannelInput {
    "source": string;
    "label": string;
}

export interface ConfigField {
    "key": string;
    "label": string;
    "type": string;
    "value"?: any;
    "options"?: ConfigFieldOption[] | null;
    "hint"?: string;
}

export interface ConfigFieldOption {
    "value": any;
    "label": string;
}

export interface LiveState {
    "status": job$0.Status;
    "runningSeconds": number;
    "text": string;
    "channels": job$0.ChannelState[] | null;
    "lastError"?: string;
}

export interface PluginOption {
    "key": string;
    "name": string;
    "description": string;
    "available": boolean;
    "needsAudio"?: boolean | null;
    "fields"?: ConfigField[] | null;

    /**
     * Audio sources only: whether this input is captured, and the speaker label
     * drawn in front of its captions. A source that is not captured still
     * carries the label it would be given, so the settings page can offer it.
     */
    "enabled"?: boolean;
    "label"?: string;
}

export interface ResourceItem {
    "id": string;
    "name": string;
    "description": string;
    "displayVersion": string;
    "local": boolean;
    "removable": boolean;
    "needsUpdate": boolean;
    "installable": boolean;
    "busy"?: boolean;
    "progress"?: number;
    "error"?: string;
}

export interface UINotification {
    "title": string;
    "message": string;
    "level": string;
}
