// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Conversation is a detected or typed question together with its answer.
 */
export interface Conversation {
    "id": number;
    "time": string;
    "question": string;
    "answer": string;
    "source": string;
    "status": string;
    "error"?: string;
}

/**
 * Insight is one key point extracted from a stretch of the transcript.
 */
export interface Insight {
    "id": number;
    "time": string;
    "text": string;
}

/**
 * State is the whole assistant view of the world, published to the UI.
 */
export interface State {
    "enabled": boolean;
    "configured": boolean;
    "summarize": boolean;
    "autoAnswer": boolean;
    "model": string;
    "provider"?: string;
    "tools": string[] | null;
    "toolNote"?: string;
    "summarizing": boolean;
    "answering": boolean;
    "pendingLines": number;
    "insights": Insight[] | null;
    "conversations": Conversation[] | null;

    /**
     * ThreadDigest is the rolling summary that stands in for the turns which no
     * longer fit a request verbatim, and DigestedTurns is how many turns it
     * covers. Both are published so the chat pane can say that the older part of
     * the conversation is still being carried, only compressed.
     */
    "threadDigest"?: string;
    "digestedTurns"?: number;
    "configError"?: string;
    "lastError"?: string;
}
