// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChannelState is one audio input's live caption line.
 */
export interface ChannelState {
    "key": string;
    "label": string;
    "text": string;
}

/**
 * HistoryEntry is one finished sentence. Speaker is the label of the audio
 * input it came from, and Channel that input's plugin key; both are empty when
 * a session captures a single unlabeled input.
 */
export interface HistoryEntry {
    "id": number;
    "time": string;
    "text": string;
    "speaker"?: string;
    "channel"?: string;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Stopped = "stopped",
    Running = "running",
    Paused = "paused",
};
