// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service represents the notifications service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckNotificationAuthorization(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.CheckNotificationAuthorization");
}

export function RegisterNotificationCategory(category: $models.NotificationCategory): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RegisterNotificationCategory", category);
}

export function RemoveAllDeliveredNotifications(): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemoveAllDeliveredNotifications");
}

export function RemoveAllPendingNotifications(): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemoveAllPendingNotifications");
}

export function RemoveDeliveredNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemoveDeliveredNotification", identifier);
}

export function RemoveNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemoveNotification", identifier);
}

export function RemoveNotificationCategory(categoryID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemoveNotificationCategory", categoryID);
}

export function RemovePendingNotification(identifier: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RemovePendingNotification", identifier);
}

/**
 * Public methods that delegate to the implementation.
 */
export function RequestNotificationAuthorization(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.RequestNotificationAuthorization");
}

export function SendNotification(options: $models.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.SendNotification", options);
}

export function SendNotificationWithActions(options: $models.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.SendNotificationWithActions", options);
}

/**
 * UpdateNotification updates an in-flight notification by ID. On macOS this
 * is auto-deduplicated by UNUserNotificationCenter; on Linux it uses the
 * D-Bus replaces_id parameter. On Windows it currently redelivers as a new
 * notification (true replace requires upstream wintoast support for tag/group).
 */
export function UpdateNotification(options: $models.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByName("github.com/wailsapp/wails/v3/pkg/services/notifications.NotificationService.UpdateNotification", options);
}
